pipeline {
	agent any
	stages {
	
		stage ('STEP1') {
		  steps {
		     echo "Hello, $FIRST_NAME $LAST_NAME"
	             echo "Welcome to $TECH demo pipeline"
	             echo "Global Parameter (CAST HOME)- $CAST_HOME_VAR"  
 		  }
		}
		
		stage ('STEP2') {
		  steps {
		     sleep 30
 		  }
		}
		
		stage ('STEP3') {
		  steps {
		     echo 'Parameter Test Done !!!'
 		  }
		}
	}
}
